name: Modifier et pousser un fichier YAML

on:
  push:
    branches:
      - main

jobs:
  modifier-et-pousser:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le référentiel source
        uses: actions/checkout@v2
        with:
          repository: EvannDev/HomeLab  # Remplacez par le propriétaire et le nom du référentiel source

      - name: Installer yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.16.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Modifier le fichier YAML
        run: |
          cat Kubernetes/idp/deployment.yaml| yq eval '(.spec.replicas) = 2' > deployment2.yaml
          mv deployment2.yaml Kubernetes/idp/deployment.yaml

      - name: Vérifier le référentiel de destination
        uses: actions/checkout@v2
        with:
          repository: EvannDev/HomeLab  # Remplacez par le propriétaire et le nom du référentiel de destination

      - name: Commit et pousser les modifications
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Modifier le fichier YAML
